FROM {{baseBuildImage}} AS builder
WORKDIR /home/builder

# copy and download dependencies - this allows us to cache dependencies
COPY . /home/builder/

ARG VERSION

RUN ./gradlew --no-daemon downloadDependencies -PexternallySuppliedVersion=$VERSION

RUN ./gradlew --no-daemon buildReleaseCandidate stageDockerArtifacts -PexternallySuppliedVersion=$VERSION

# copy artifacts and package image
FROM {{baseContainerImage}}

RUN /usr/sbin/addgroup {{runAsGroup}} \
&& /usr/sbin/adduser -D {{runAsUser}} -G {{runAsGroup}}

WORKDIR /home/app
COPY --from=builder /home/builder/build/docker/* ./

RUN chown app /home/app/shim.sh \
&& chmod 700 /home/app/shim.sh

## Install envconsul
USER root

RUN apk add --update ca-certificates openssl \
&& update-ca-certificates \
&& wget -O envconsul.tgz https://github.com/the-container-store/envconsul/releases/download/0.7.3-42-eba5c96/envconsul_0.7.3-42-eba5c96_linux-amd64.tgz \
&& tar -xvzf envconsul.tgz \
&& ln -sf $PWD/envconsul /usr/local/bin

USER {{runAsUser}}
EXPOSE {{exposePort}}

ENTRYPOINT envconsul -config "/home/app/{{consulConfigurationFileName}}"