FROM {{baseBuildImage}} AS builder
WORKDIR /home/builder

# copy and download dependencies - this allows us to cache dependencies
COPY . /home/builder/

ARG VERSION

RUN ./gradlew --no-daemon downloadDependencies -PexternallySuppliedVersion=$VERSION

RUN ./gradlew --no-daemon buildReleaseCandidate stageDockerArtifacts -PexternallySuppliedVersion=$VERSION

# copy artifacts and package image
FROM {{baseContainerImage}}

USER root

RUN ./{{osPackageManager}}-install-prerequisites.sh \
#
# Install envconsul
#
&& wget -q -O consul-template.zip https://releases.hashicorp.com/consul-template/0.19.5/consul-template_0.19.5_linux_386.zip \
&& unzip consul-template.zip -d /usr/local/bin \
&& rm consul-template.zip \
#
# Configure app user and group
#
&& usr/sbin/addgroup {{runAsGroup}} \
&& /usr/sbin/adduser -D {{runAsUser}} -G {{runAsGroup}}

WORKDIR /home/app
COPY --from=builder /home/builder/build/docker/* ./

RUN chown app /home/app/shim.sh \
&& chmod 700 /home/app/shim.sh

USER {{runAsUser}}
EXPOSE {{exposePort}}

CMD consul-template \
        -exec-reload-signal=SIGUSR1 \
        -exec "/bin/bash -c \"trap '' SIGUSR1; /home/app/shim.sh\""
