FROM {{baseBuildImage}} AS builder
WORKDIR /home/builder

# copy and download dependencies - this allows us to cache dependencies
COPY . /home/builder/

ARG VERSION

RUN ./gradlew --no-daemon downloadDependencies -PexternallySuppliedVersion=$VERSION

RUN ./gradlew --no-daemon buildReleaseCandidate stageDockerArtifacts -PexternallySuppliedVersion=$VERSION

# copy artifacts and package image
FROM {{baseExecContainerImage}}
RUN yum -y update \
 && {{baseExecContainerImageExtras}} \
 && yum -y install {{baseImageJDK}} \
 && yum clean all \
## Install envconsul
 && yum -y install openssl tar.x86_64 \
 && curl -o envconsul.tgz -L {{envConsulTgz}} \ 
 && tar -xvzf envconsul.tgz \
 && ln -sf $PWD/envconsul /usr/local/bin \
## Configure app user and group
 && /usr/sbin/addgroup {{runAsGroup}} \
 && /usr/sbin/adduser -D {{runAsUser}} -G {{runAsGroup}}

WORKDIR /home/app
COPY --from=builder /home/builder/build/docker/* ./

RUN chown app /home/app/shim.sh \
 && chmod 700 /home/app/shim.sh

USER {{runAsUser}}
EXPOSE {{exposePort}}

ENTRYPOINT envconsul -config="/home/app/{{consulConfigurationFileName}}"